spring:
  h2:
    console:
      settings:
        trace: false
        web-allow-others: false
      path: /h2-console
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    password: ''
    driver-class-name: org.h2.Driver
    username: ''
    url: jdbc:h2:mem:testdb
server:
  port: 5000
